Management/urls.py
from django.urls import path

from Management import views

urlpatterns = [
    #path('', views.upload, name='index'),
    path('settings/', views.settings_view, name='settings'),
    path('upload/', views.upload_view, name='upload'),
    path('transporters/', views.set_station_transporters_view, name='set_station_transporters'),
    path('transporters/stations', views.set_station_transporters_view, name='set_station_transporters'),
    path('routes/', views.RouteListView.as_view(), name='route_list'),
    path('routes/create/', views.RouteCreateView.as_view(), name='route_create'),
    path('routes/<int:pk>/', views.RouteUpdateView.as_view(), name='route_update'),
    path('routes/<int:pk>/delete/', views.RouteDeleteView.as_view(), name='route_delete'),

    path('cities/', views.city_for_station_view, name='city_for_station')

]

Site/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
]

Transporter/urls.py
"""Transporter URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an upload:  from my_app upload views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an upload:  from other_app.views upload Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls upload include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Site.urls')),
    path('admin/', admin.site.urls),
    path('management/', include('Management.urls')),
]

Management/models/city.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class City(models.Model):
    """
    Model that represents the City.
    """
    id = models.AutoField(primary_key=True)  # Identifier of the City.
    name = models.CharField(_("City name"), max_length=100, blank=False, null=False, unique=True)  # City Name.
    station = models.ForeignKey('Station', on_delete=models.CASCADE, related_name='cites', related_query_name='city')

Management/models/transporter.py
from django.db import models

class Transporter(models.Model):
    SMALL_TRANSPORTER = 'S'
    MEDIUM_TRANSPORTER = 'M'
    LARGE_TRANSPORTER = 'L'
    TRANSPORTER_SIZE_CHOICES = [
        (SMALL_TRANSPORTER, 'Small'),
        (MEDIUM_TRANSPORTER, 'Medium'),
        (LARGE_TRANSPORTER, 'Large'),

    ]
    stations = models.ManyToManyField(to='Station',
                                      related_name='transporters',
                                      related_query_name='transporter',
                                      through='TransporterForCity')

    size = models.CharField(max_length=1,
                            choices=TRANSPORTER_SIZE_CHOICES,
                            blank=False,
                            null=False)

    number = models.IntegerField(blank=False,
                                 null=False)

    platform = models.IntegerField(blank=False,
                                   null=False,
                                   unique=True)

    soldiers = models.ForeignKey


class TransporterForCity(models.Model):
    transporter = models.ForeignKey('Transporter',
                                    on_delete=models.CASCADE)

    station = models.ForeignKey('Station',
                                on_delete=models.CASCADE)

    occupied_seats = models.IntegerField(default=0)

Management/forms/city.py
from django import forms

from Management.models import City
#
#
# class CityForm(forms.ModelForm):
#
#     class Meta:
#         model = City

CityFormSet = forms.modelformset_factory(City, fields=('name', 'station', 'id'), can_delete=True)

Management/forms/route.py
from django import forms
from django.core.exceptions import ValidationError

from Management.models import Route



class RouteModelForm(forms.ModelForm):
    def clean_name(self):
        data = self.cleaned_data['name']
        if Route.objects.filter(name=data).exclude(pk=self.instance.pk).exists():
            self.add_error('name',"Route already exist")
        return data

    class Meta:
        model = Route
        fields = ('name', 'id' )
        labels = {
            'name': 'Route Name'
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'forms-control forms-control-lg',
                }
            )
        }

Management/forms/settings.py
from Management.models import Settings
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

class SettingsModelForm(forms.ModelForm):

    def clean_big_transporter_size(self):
        big_size = self.cleaned_data['big_transporter_size']

        return big_size

    def clean_medium_transporter_size(self):
        medium_size = self.cleaned_data['medium_transporter_size']
        big_size = self.cleaned_data['big_transporter_size']

        if big_size > medium_size:
            return medium_size

        self.add_error('medium_transporter_size', _('medium transporter must have less seats then big transporter.'))
        return medium_size

    def clean_small_transporter_size(self):
        small_size = self.cleaned_data['small_transporter_size']
        medium_size = self.cleaned_data['medium_transporter_size']
        if medium_size > small_size:
            return small_size

        self.add_error('small_transporter_size', _('small transporter must have less seats then medium transporter.'))
        return small_size





    class Meta:
        model = Settings
        fields = ['big_transporter_size', 'medium_transporter_size', 'small_transporter_size']
        labels = {
            'big_transporter_size' : _('Big Transporter'),
            'medium_transporter_size': _('Medium Transporter'),
            'small_transporter_size': _('Small Transporter'),
        }
        widgets = {
            'big_transporter_size': forms.NumberInput(attrs={
                'min' : 1
            }),
            'medium_transporter_size': forms.NumberInput(attrs={
                'min': 1
            }),
            'small_transporter_size': forms.NumberInput(attrs={
                'min': 1
            }),
        }

Management/forms/station.py
from django import forms

from Management.models import Route, Station

StationFormSet = forms.inlineformset_factory(parent_model=Route,
                                             model=Station,
                                             fields=('name','id'),
                                             extra=1)

Management/views/city.py
from django.shortcuts import render
from Management.forms import CityFormSet

def city_for_station_view(request):
    if request.method == 'GET':
        city_formset = CityFormSet()
        return render(request, "Management/city/list.html", {'formset' : city_formset})

    city_formset = CityFormSet(request.POST)

    if city_formset.is_valid():
        city_formset.save()

    return render(request, "Management/city/list.html", {'formset': city_formset})

Management/views/route.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy, reverse

from Management.forms import RouteModelForm
from Management.forms.station import StationFormSet
from Management.models import Route, Station
from django.shortcuts import get_object_or_404

class RouteListView(generic.ListView):
    model = Route
    template_name = 'Management/route/list.html'
    context_object_name = 'routes'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(RouteListView, self).get_context_data(**kwargs)
        routes = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(routes, self.paginate_by)
        try:
            routes = paginator.page(page)
        except PageNotAnInteger:
            routes = paginator.page(1)
        except EmptyPage:
            routes = paginator.page(paginator.num_pages)
        context['routes'] = routes
        return context

class RouteCreateView(generic.CreateView):
    model = Route
    template_name = 'Management/route/create.html'
    success_url = reverse_lazy('route_list')
    form_class = RouteModelForm

    def post(self, request, *args, **kwargs):
        station_formset = StationFormSet(request.POST)
        route_form = RouteModelForm(data=request.POST)
        if station_formset.is_valid() and route_form.is_valid():
            return self.form_valid(station_formset, route_form)

    def form_valid(self, station_formset, route_form):
        route = route_form.save()
        stations = station_formset.save(commit=False)
        for deleted_station in station_formset.deleted_objects:
            deleted_station.delete()
        for station in stations:
            station.route = route
            station.save()

        return HttpResponseRedirect(self.success_url)


    def get_context_data(self, **kwargs):
        context = super(RouteCreateView, self).get_context_data(**kwargs)
        context['station_formset'] = StationFormSet(queryset=Station.objects.none())
        context['route_form'] = RouteModelForm()
        return context

class RouteUpdateView(generic.UpdateView):
    model = Route
    template_name = 'Management/route/update.html'
    success_url = reverse_lazy('route_list')
    form_class = RouteModelForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        station_formset = StationFormSet(request.POST, instance=self.object)
        route_form = RouteModelForm(data=request.POST, instance=self.object)
        if station_formset.is_valid() and route_form.is_valid():
            return self.form_valid(station_formset, route_form)
        else:
            return self.form_invalid(station_formset = station_formset, route_form =route_form)

    def form_valid(self, station_formset, route_form):
        route = route_form.save()
        stations = station_formset.save(commit=False)
        for deleted_station in station_formset.deleted_objects:
            deleted_station.delete()
        for station in stations:
            station.route = route
            station.save()

        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, station_formset, route_form, **kwargs):
        """If the form is invalid, render the invalid form."""
        context = self.get_context_data(**kwargs)
        context['station_formset'] = station_formset
        context['route_form'] = route_form
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(RouteUpdateView, self).get_context_data(**kwargs)
        context['station_formset'] = StationFormSet(instance=self.object)
        context['route_form'] = RouteModelForm(instance=self.object)
        return context

class RouteDeleteView(generic.DeleteView):
    model = Route
    template_name = 'Management/route/delete.html'
    success_url = reverse_lazy('route_list')

Management/views/settings.py
from django.shortcuts import render
from Management import forms
from Management.models import Settings


def settings_view(request):

    if request.method == 'GET':
        settings_form = forms.SettingsModelForm(instance= Settings.objects.get_settings())
    else:
        settings_form = forms.SettingsModelForm(request.POST, instance= Settings.objects.get_settings())

        if settings_form.is_valid():
            settings_form.save()

    return render(request, 'Management/settings/form.html', {'form' : settings_form})

Management/views/transporter.py
from django.db.models import Count, Min
from django.shortcuts import render

from Management.models import Station, Transporter
from Management.mechanisms.organization import ORGANIZATIONS
from Management.forms import TransporterFormSet


def __create_transporters(transporter_data, platform, station_id):
    for transporter_number in range(1, transporter_data['count'] + 1):
        transporter = Transporter.objects.create(size=transporter_data['size_symbol'],
                                                 platform=platform,
                                                 number=transporter_number)
        occupied_seats_count = min(transporter_data['occupied_seats'], transporter_data['size'])
        transporter_data['occupied_seats'] = max(transporter_data['occupied_seats'] - transporter_data['size'], 0)
        transporter.stations.add(station_id, through_defaults={'occupied_seats': occupied_seats_count})

        platform = platform + 1
    return platform


def set_station_transporters_view(request):
    if request.method == 'GET':
        cites_soldiers_count = Station.objects.annotate(soldiers_count=Count('soldier')).values('id', 'name',
                                                                                                'soldiers_count')
        ORGANIZATIONS['AVG'](cites_soldiers_count)
        transporter_formset = TransporterFormSet(initial=cites_soldiers_count)
        return render(request, 'Management/transporter/form.html', {'formset': transporter_formset})

    transporter_formset = TransporterFormSet(request.POST)

    if not transporter_formset.is_valid():
        return render(request, 'Management/transporter/form.html', {'formset': transporter_formset})

    Transporter.objects.all().delete()
    platform = 1
    for transporter_data in transporter_formset.cleaned_data:
        transporter = transporter_data['big_transporter']
        transporter['size_symbol'] = Transporter.LARGE_TRANSPORTER
        transporter['occupied_seats'] = min(transporter_data['soldiers_count'], transporter['occupied_seats'])
        transporter_data['soldiers_count'] = transporter_data['soldiers_count'] - transporter['occupied_seats']
        platform = __create_transporters(transporter_data=transporter,
                                         platform=platform,
                                         station_id=transporter_data['id'])

        transporter = transporter_data['medium_transporter']
        transporter['size_symbol'] = Transporter.MEDIUM_TRANSPORTER
        transporter['occupied_seats'] = min(transporter_data['soldiers_count'], transporter['occupied_seats'])
        transporter_data['soldiers_count'] = transporter_data['soldiers_count'] - transporter['occupied_seats']
        platform = __create_transporters(transporter_data=transporter,
                                         platform=platform,
                                         station_id=transporter_data['id'])

        transporter = transporter_data['small_transporter']
        transporter['size_symbol'] = Transporter.SMALL_TRANSPORTER
        transporter['occupied_seats'] = min(transporter_data['soldiers_count'], transporter['occupied_seats'])
        transporter_data['soldiers_count'] = transporter_data['soldiers_count'] - transporter['occupied_seats']
        platform = __create_transporters(transporter_data=transporter,
                                         platform=platform,
                                         station_id=transporter_data['id'])

    return render(request, 'Management/transporter/form.html', {'formset': transporter_formset})


def set_transporter_stations_view(request):
    pass

Management/views/upload.py
from django.db.models import Model
from django.shortcuts import render
from django.urls import reverse_lazy

from Management.mechanisms.upload import IMPORTS
from Management.forms import UploadForm, ValidationError
from Management.models import Soldier, Station, City
import os.path
from django.shortcuts import redirect


SOLDIER_ID = 'מספר אישי'
SOLDIER_TAGS = 'תגיות - הוספה'
SOLDIER_FIRST_NAME = 'שם פרטי'
SOLDIER_LAST_NAME = 'שם משפחה'
SOLDIER_CITY = 'עיר'
SOLDIER_PHONE = 'טלפון'

def __get_soldier_station(city):
    try:
        return Station.objects.get(name=city)
    except Station.DoesNotExist:
        return City.objects.get(name=city).station

def upload_view(request):
    if request.method == "GET":
        form = UploadForm()
        return render(request, 'Management/upload/form.html', {'form': form})

    form = UploadForm(request.POST, request.FILES)

    if not form.is_valid():
        return render(request, 'Management/upload/form.html', {'form': form})

    source = request.FILES['file']
    extension = os.path.splitext(source.name)[1]
    import_mechanism = IMPORTS[extension]
    try:
        data = import_mechanism(source)
        Soldier.objects.all().delete()
        for soldier_data in data:
            city = soldier_data[SOLDIER_CITY]
            Soldier.objects.create(identification_number=soldier_data[SOLDIER_ID],
                                   first_name=soldier_data[SOLDIER_FIRST_NAME],
                                   last_name=soldier_data[SOLDIER_LAST_NAME],
                                   structure=soldier_data[SOLDIER_TAGS],
                                   city=city,
                                   station= __get_soldier_station(city))
        return redirect(reverse_lazy('home'))

    except ValidationError as e:
        form.add_error('file', e.message)
        return render(request, 'Management/upload/form.html', {'form': form})

Management/templates/Management/route/create.html
{% extends "base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Create Route</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ route_form.as_p }}

                {{ station_formset.management_form }}

                <div class="col-2">
                    <label>Stations:</label>

                </div>
                {% for form in station_formset %}
                    <div class="col-4 form-group spacer station-row">
                        <div class="input-group">
                            {{ form.name }}
                            {{ form.name.errors }}

                            <div class="input-group-append">
                                <button class="btn btn-danger delete-button">-</button>
                                <input type="checkbox" style="display:none"  id="id_{{ form.prefix }}-{{ form.DELETE.name }}" name="{{ form.prefix }}-{{ form.DELETE.name }}">
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group spacer col-3">
                    <button type="button" class="btn btn-block btn-primary add-button">Add</button>
                </div>
                <button type="submit" class="btn btn-success" value="submit">Save</button>
                <button type="button" class="btn btn-primary" onclick="location.href = '{% url 'route_list' %}';">
                    Cancel
                </button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}

    <script>
        $('.add-button').on('click', function (e) {
            e.preventDefault()
            var newRow = $('.station-row:last').clone(true);
            newRow.css("display", "");
            var rowCount = $('#id_stations-TOTAL_FORMS').val();
            newRow.find("input:text").each(function () {
                var name = $(this).attr('name').replace('-' + (rowCount - 1) + '-', '-' + rowCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('')
            });
            newRow.find("input:hidden").each(function () {
                var name = $(this).attr('name').replace('-' + (rowCount - 1) + '-', '-' + rowCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('')
            });
            newRow.find("input:checkbox").each(function () {
                var name = $(this).attr('name').replace('-' + (rowCount - 1) + '-', '-' + rowCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).prop('checked', false);
            });
            rowCount++;
            $('#id_stations-TOTAL_FORMS').val(rowCount);
            $('.station-row:last').after(newRow);

            return false;
        });
        $('.delete-button').on('click', function (e) {
           e.preventDefault();
           $(this).parents('.station-row').css("display", "none");
           $(this).parent('.input-group-append').find(':checkbox').prop('checked', true);;
           return false;
        });

    </script>
{% endblock js %}

Management/templates/Management/route/delete.html
{% extends "base.html" %}

{% block content %}
    <div class="card">
    <div class="card-header">
        <h5 class="card-title">Delete Route {{object.name}}</h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                Are you sure you want to delete <strong>{{ object.name }}</strong> ?
            </div>
            <button type="submit" class="btn btn-danger">Delete</button>
            <button type="button" class="btn btn-primary" onclick="location.href = '{% url 'route_list' %}';">Cancel</button>

        </form>
    </div>
</div>
{% endblock content %}

Management/templates/Management/route/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <table class="table table-hover">
              <caption>
                  <button type="button" class="btn btn-primary"
                                    onclick="location.href ='{% url 'route_create' %}';">
                                    Add Route
                  </button>
              </caption>
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="w-75">Name</th>
                    <th scope="col" ></th>

                </tr>
            </thead>
            <tbody>
                {% for route in routes %}
                    <tr scope="row">
                        <td>{{route.name}}</td>
                         <td><div class="text-right">
                            <button type="button" class="btn btn-primary"
                                    onclick="location.href ='{% url 'route_update' route.pk %}';">
                                    Edit
                            </button>
                             <button type="button" class="btn btn-danger"
                                    onclick="location.href ='{% url 'route_delete' route.pk %}';">
                                    Delete
                            </button>
                                 </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
    </table>
    {% if is_paginated %}
        {% include "Management/_pagination.html" %}
    {% endif %}

{% endblock %}

Management/templates/Management/route/update.html
{% extends "base.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Create Route</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ route_form.as_p }}

                {{ station_formset.management_form }}

                <div class="col-2">
                    <label>Stations:</label>

                </div>
                {% for form in station_formset %}
                    <div class="col-4 form-group spacer station-row">
                        <div class="input-group">
                            {{ form.id }}
                            {{ form.name }}
                            {{ form.name.errors }}
                            <div class="input-group-append">
                                <button class="btn btn-danger delete-button">-</button>
                                <input type="checkbox" style="display:none"  id="id_{{ form.prefix }}-{{ form.DELETE.name }}" name="{{ form.prefix }}-{{ form.DELETE.name }}">
                            </div>
                        </div>
                        {{ form.non_field_errors }}
                    </div>
                {% endfor %}
                <div class="form-group spacer col-3">
                    <button type="button" class="btn btn-block btn-primary add-button">Add</button>
                </div>
                {{ station_formset.non_field_errors }}
                <button type="submit" class="btn btn-success" value="submit">Save</button>
                <button type="button" class="btn btn-primary" onclick="location.href = '{% url 'home' %}';">
                    Cancel
                </button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}

    <script>
        $('.add-button').on('click', function (e) {
            e.preventDefault()
            var newRow = $('.station-row:last').clone(true);
            newRow.css("display", "");
            var rowCount = $('#id_stations-TOTAL_FORMS').val();
            newRow.find("input:text").each(function () {
                var name = $(this).attr('name').replace('-' + (rowCount - 1) + '-', '-' + rowCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('')
            });
            newRow.find("input:checkbox").each(function () {
                var name = $(this).attr('name').replace('-' + (rowCount - 1) + '-', '-' + rowCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).prop('checked', false);
            });
            newRow.find("input:hidden").each(function () {
                var name = $(this).attr('name').replace('-' + (rowCount - 1) + '-', '-' + rowCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('')
            });
            rowCount++;
            $('#id_stations-TOTAL_FORMS').val(rowCount);
            $('.station-row:last').after(newRow);

            return false;
        });
        $('.delete-button').on('click', function (e) {
           e.preventDefault();
           $(this).parents('.station-row').css("display", "none");
           $(this).parent('.input-group-append').find(':checkbox').prop('checked', true);;
           return false;
        });

    </script>
{% endblock js %}